name: Build project using muddler and upload artifact

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Muddle
        uses: demonnic/build-with-muddler@main
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coffeemud-gui
          path: build/tmp/